export const COLLECTION_CATEGORY = [
  // { value: 'talken', title: 'Talken' },
  // { value: 'art', title: 'Art' },
  // { value: 'collectibles', title: 'Collectibles' },
  // { value: 'membership', title: 'Membership' },
  // { value: 'pieces', title: 'Pieces' },
  // { value: 'games', title: 'Games' },
  // { value: 'virtual', title: 'Virtual Worlds' },
  { value: 'all', title: 'All' },
  { value: 'art', title: 'Art' },
  { value: 'collectable', title: 'Collectable' },
  { value: 'peps', title: 'PFPs' },
  { value: 'gaming', title: 'Gaming' },
  { value: 'sports', title: 'Sports' },
  { value: 'photography', title: 'Photography' },
];
