export const COLLECTION_CATEGORY = [
  // { value: 'talken', title: 'Talken' },
  // { value: 'art', title: 'Art' },
  // { value: 'collectibles', title: 'Collectibles' },
  // { value: 'membership', title: 'Membership' },
  // { value: 'pieces', title: 'Pieces' },
  // { value: 'games', title: 'Games' },
  // { value: 'virtual', title: 'Virtual Worlds' },
  { value: 'art', title: 'Art' },
  { value: 'gameItem', title: 'Game Item' },
  { value: 'music', title: 'Music' },
  { value: 'car', title: 'Car' },
  { value: 'house', title: 'House' },
  { value: 'nftProject', title: 'NFT Project' },
  { value: 'virtualLand', title: 'Virtual Land' },
];
